name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  native_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            artifact_name: chat-gpt-cli-macos-intel
          - os: ubuntu-latest
            artifact_name: chat-gpt-cli-linux64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GraalVM with Native Image
        uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Native Image
        run: gu install native-image

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build native image
        run: ./mvnw -Pnative native:compile

      - name: Upload native image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact_name }}
          path: target/chat-gpt-cli

  create_release:
    needs: native_build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract tag name
        id: extract_tag
        run: |
          echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          tag_name: ${{ steps.extract_tag.outputs.tag }}
          release_name: Release ${{ steps.extract_tag.outputs.tag }}
          draft: false
          prerelease: false

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: chat-gpt-cli-macos-intel
          path: artifacts/chat-gpt-cli-macos-intel

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: chat-gpt-cli-linux64
          path: artifacts/chat-gpt-cli-linux64

      - name: Upload native images
        run: |
          for artifact_name in chat-gpt-cli-macos-intel chat-gpt-cli-linux64; do
            echo "Uploading ${artifact_name}"
            gh release upload ${{ steps.extract_tag.outputs.tag }} artifacts/${artifact_name}/chat-gpt-cli
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
